import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case cs
    case en

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .cs: return "Čeština"
        case .en: return "English"
        }
    }
}

enum L10n {
    static func text(_ key: String, language: AppLanguage) -> String {
        let table = language == .cs ? cs : en
        return table[key] ?? en[key] ?? key
    }

    static func format(_ key: String, language: AppLanguage, _ arguments: CVarArg...) -> String {
        String(format: text(key, language: language), locale: Locale(identifier: language.rawValue), arguments: arguments)
    }

    private static let cs: [String: String] = [
        "app.subtitle": "Nativní aplikace pro macOS založená na yt-dlp",
        "source.title": "Odkaz",
        "source.placeholder": "https://…",
        "source.clipboard": "Vložit ze schránky",
        "source.analyzing": "Načítám…",
        "source.analyze": "Načíst informace",
        "source.add": "Přidat do fronty",
        "media.found": "Nalezené médium",
        "media.qualityAutomatic": "Dostupná kvalita se určí automaticky při stahování.",
        "media.availableHeights": "Dostupná rozlišení: %@",
        "media.playlistContext": "Odkaz je součástí playlistu",
        "media.playlistContextNamed": "Součást playlistu: %@",
        "queueSettings.title": "Nastavení celé fronty",
        "queueSettings.help": "Tato nastavení se použijí na všechny položky, které spustíš tlačítkem Stáhnout frontu.",
        "outputType": "Typ výstupu",
        "video": "Video",
        "audio": "Zvuk",
        "videoFormat": "Formát videa",
        "audioFormat": "Formát zvuku",
        "maxQuality": "Maximální kvalita",
        "best": "Nejlepší dostupná",
        "size.currentEstimate": "Odhad velikosti pro načtené video: ~%@",
        "size.jobEstimate": "Odhad: ~%@",
        "size.queueEstimate": "Odhad čekající fronty: ~%@",
        "size.queueEstimateWithUnknown": "Odhad čekající fronty: ~%@ · bez odhadu: %d",
        "size.queueUnknown": "Velikost čekající fronty zatím nelze odhadnout",
        "size.unavailable": "Velikost tohoto výstupu zatím nelze odhadnout",
        "size.playlistUnknown": "velikost celého playlistu není předem spočítaná",
        "size.help": "Jde o přibližný odhad podle streamů dostupných z yt-dlp; po převodu přes ffmpeg se výsledná velikost může lišit.",
        "youtubeCookies": "Cookies pro YouTube",
        "youtubeCookies.none": "Bez cookies",
        "youtubeCookies.help": "Při anti-bot chybě vyber prohlížeč, ve kterém jsi přihlášený k YouTube.",
        "scope.single": "Jedno video",
        "scope.playlist": "Celý playlist",
        "playlistPrompt.title": "Toto video je v playlistu",
        "playlistPrompt.message": "Odkaz obsahuje také playlist. Co chceš přidat do fronty?",
        "playlistPrompt.messageNamed": "Video je součástí playlistu „%@“. Co chceš přidat do fronty?",
        "playlistPrompt.single": "Jen toto video",
        "playlistPrompt.all": "Celý playlist",
        "playlistPrompt.cancel": "Zrušit",
        "embedThumbnail": "Vložit náhled jako obal souboru",
        "embedThumbnail.webmNote": "WebM nepodporuje vložení obalu tímto způsobem. Pro video s obalem použij MP4.",
        "subtitles.download": "Stáhnout titulky",
        "subtitles.languages": "Jazyky titulků",
        "subtitles.placeholder": "cs,en nebo all",
        "subtitles.automatic": "Zahrnout automatické titulky",
        "subtitles.embed": "Vložit titulky do videa",
        "destination": "Cílová složka",
        "chooseFolder": "Vybrat složku…",
        "choose": "Vybrat",
        "queue.title": "Fronta",
        "queue.empty": "Fronta je prázdná. Přidej jeden nebo více odkazů.",
        "queue.clearFinished": "Odstranit dokončené",
        "queue.download": "Stáhnout frontu",
        "queue.downloading": "Stahování probíhá…",
        "queue.stop": "Zastavit stahování",
        "queue.stopping": "Zastavuji…",
        "queue.remove": "Odebrat z fronty",
        "queue.pendingCount.one": "%d položka čeká",
        "queue.pendingCount.many": "%d položek čeká",
        "state.queued": "Čeká",
        "state.downloading": "Stahuje se",
        "state.processing": "Zpracovává se",
        "state.completed": "Hotovo",
        "state.failed": "Chyba",
        "eta": "Zbývá %@",
        "history.title": "Historie",
        "history.clear": "Smazat historii",
        "history.empty": "Historie je prázdná",
        "history.emptyHelp": "Dokončená stahování se zobrazí tady.",
        "history.reveal": "Zobrazit ve Finderu",
        "settings.title": "Nastavení",
        "settings.language": "Jazyk aplikace",
        "settings.languageHelp": "Změna se projeví okamžitě v hlavním okně. Systémové položky nabídky macOS se řídí jazykem systému.",
        "settings.downloads": "Stahování",
        "menu.pasteURL": "Vložit URL ze schránky",
        "error.invalidURL": "Vlož platnou adresu začínající http:// nebo https://.",
        "error.missingYTDLP": "Program yt-dlp nebyl nalezen. Nainstaluj ho příkazem: brew install yt-dlp",
        "error.missingFFmpeg": "Pro převody, slučování a vkládání náhledů jsou potřeba ffmpeg a ffprobe. Nainstaluj je příkazem: brew install ffmpeg",
        "error.invalidMetadata": "yt-dlp vrátil informace, které se nepodařilo přečíst.",
        "error.downloadFailed": "Stahování se nezdařilo.",
        "error.youtubeBlocked.none": "YouTube požadavek odmítl (anti-bot / chyba přehrávacího klienta). V nastavení fronty vyber prohlížeč, ve kterém jsi přihlášený k YouTube, případně v něm nejdřív dokonči CAPTCHA nebo kontrolu přihlášení.",
        "error.youtubeBlocked.browser": "YouTube požadavek stále odmítá, přestože jsou použity cookies z prohlížeče %@. Otevři v něm YouTube, ověř přihlášení nebo případnou CAPTCHA a zkus to znovu.",
        "tools.missingYTDLP": "yt-dlp nebyl nalezen · brew install yt-dlp ffmpeg",
        "tools.missingFFmpeg": "yt-dlp je připraven, ale chybí ffmpeg/ffprobe · brew install ffmpeg",
        "tools.ready": "yt-dlp + ffmpeg/ffprobe jsou připraveny"
    ]

    private static let en: [String: String] = [
        "app.subtitle": "Native macOS app powered by yt-dlp",
        "source.title": "Link",
        "source.placeholder": "https://…",
        "source.clipboard": "Paste from Clipboard",
        "source.analyzing": "Loading…",
        "source.analyze": "Load Info",
        "source.add": "Add to Queue",
        "media.found": "Found Media",
        "media.qualityAutomatic": "Available quality will be selected automatically when downloading.",
        "media.availableHeights": "Available resolutions: %@",
        "media.playlistContext": "This link is part of a playlist",
        "media.playlistContextNamed": "Part of playlist: %@",
        "queueSettings.title": "Queue Settings",
        "queueSettings.help": "These settings apply to every queued item started with Download Queue.",
        "outputType": "Output Type",
        "video": "Video",
        "audio": "Audio",
        "videoFormat": "Video Format",
        "audioFormat": "Audio Format",
        "maxQuality": "Maximum Quality",
        "best": "Best Available",
        "size.currentEstimate": "Estimated size for loaded video: ~%@",
        "size.jobEstimate": "Estimate: ~%@",
        "size.queueEstimate": "Estimated waiting queue: ~%@",
        "size.queueEstimateWithUnknown": "Estimated waiting queue: ~%@ · without estimate: %d",
        "size.queueUnknown": "The waiting queue size cannot be estimated yet",
        "size.unavailable": "This output size cannot be estimated yet",
        "size.playlistUnknown": "full playlist size is not pre-calculated",
        "size.help": "This is an approximate estimate based on streams reported by yt-dlp; ffmpeg conversion can change the final size.",
        "youtubeCookies": "YouTube Cookies",
        "youtubeCookies.none": "No cookies",
        "youtubeCookies.help": "If YouTube returns an anti-bot error, select a browser where you are signed in to YouTube.",
        "scope.single": "Single video",
        "scope.playlist": "Entire playlist",
        "playlistPrompt.title": "This video is in a playlist",
        "playlistPrompt.message": "The link also contains a playlist. What would you like to add to the queue?",
        "playlistPrompt.messageNamed": "This video is part of the playlist “%@”. What would you like to add to the queue?",
        "playlistPrompt.single": "Just This Video",
        "playlistPrompt.all": "Entire Playlist",
        "playlistPrompt.cancel": "Cancel",
        "embedThumbnail": "Embed thumbnail as file artwork",
        "embedThumbnail.webmNote": "WebM does not support embedded cover artwork this way. Use MP4 if you want artwork embedded in the video file.",
        "subtitles.download": "Download subtitles",
        "subtitles.languages": "Subtitle languages",
        "subtitles.placeholder": "cs,en or all",
        "subtitles.automatic": "Include automatic subtitles",
        "subtitles.embed": "Embed subtitles in video",
        "destination": "Destination Folder",
        "chooseFolder": "Choose Folder…",
        "choose": "Choose",
        "queue.title": "Queue",
        "queue.empty": "The queue is empty. Add one or more links.",
        "queue.clearFinished": "Remove Finished",
        "queue.download": "Download Queue",
        "queue.downloading": "Downloading…",
        "queue.stop": "Stop Downloading",
        "queue.stopping": "Stopping…",
        "queue.remove": "Remove from Queue",
        "queue.pendingCount.one": "%d item waiting",
        "queue.pendingCount.many": "%d items waiting",
        "state.queued": "Waiting",
        "state.downloading": "Downloading",
        "state.processing": "Processing",
        "state.completed": "Done",
        "state.failed": "Error",
        "eta": "%@ remaining",
        "history.title": "History",
        "history.clear": "Clear History",
        "history.empty": "No download history",
        "history.emptyHelp": "Completed downloads will appear here.",
        "history.reveal": "Show in Finder",
        "settings.title": "Settings",
        "settings.language": "App Language",
        "settings.languageHelp": "The main window updates immediately. Standard macOS menu items follow the system language.",
        "settings.downloads": "Downloads",
        "menu.pasteURL": "Paste URL from Clipboard",
        "error.invalidURL": "Enter a valid address starting with http:// or https://.",
        "error.missingYTDLP": "yt-dlp was not found. Install it with: brew install yt-dlp",
        "error.missingFFmpeg": "ffmpeg and ffprobe are required for conversion, merging, and thumbnail embedding. Install them with: brew install ffmpeg",
        "error.invalidMetadata": "yt-dlp returned media information that could not be read.",
        "error.downloadFailed": "The download failed.",
        "error.youtubeBlocked.none": "YouTube rejected the request (anti-bot / player-client error). In Queue Settings, select a browser where you are signed in to YouTube. If necessary, complete any CAPTCHA or sign-in check in that browser first.",
        "error.youtubeBlocked.browser": "YouTube is still rejecting the request while using cookies from %@. Open YouTube in that browser, verify your sign-in or any CAPTCHA, then try again.",
        "tools.missingYTDLP": "yt-dlp not found · brew install yt-dlp ffmpeg",
        "tools.missingFFmpeg": "yt-dlp is ready, but ffmpeg/ffprobe are missing · brew install ffmpeg",
        "tools.ready": "yt-dlp + ffmpeg/ffprobe are ready"
    ]
}
